### ISSUE TITLE
Draw Image coordinates

### ISSUE THREAD

**Issue by NickyTesla** [Grille98/webgl2D#2]
Hi, I thought I would test out this library to get some performance benefits out of a canvas animation involving a large number of images.  

Generally it works great, but I'm having some issues when animating images at fractional positions.  

If their velocity vector is not moving an image exactly 1 pixel per frame then the renderer seems to 'step' or round the image to the nearest pixel?

It results in a very jittery animation.  I was wondering if I'm doing something wrong, or if there's some configuration that needs to be done to achieve a smooth animation at the sub-pixel level.

**Comment by Grille** [comment]
Hi

This library was originally made for stuff like pixel art.
Because of that antialiasing and image filtering were disabled.

That's why it's jumping.

I have now added that both can be optionally activated.

That should solve your problem.

**Comment by NickyTesla** [comment]
Yep, works like a charm, thanks for updating it!
